In [1]:
# Reconfigurar para salvar sem falhas
import pandas as pd
from geopy.geocoders import Nominatim
import time

In [2]:
# Recarregar o arquivo
file_path = r'C:\Users\Administrator\Documents\projetos_py\unlimitail\Blocos e Trios elétricos - CEP.xlsx'
df = pd.read_excel(file_path)

# Configurar geolocalizador
geolocator = Nominatim(user_agent="geoapi")

df.head()

,Nome da tela / nome do local,UF,Cidade,Bairro,Endereço,CEP
0,CONV ESTADIO DO GUEDALA LTDA,São Paulo,SAO PAULO,MORUMBI (VILA PROGREDIOR),"AVENIDA JORGE JOÃO SAAD, 161/165, SAO PAULO, S...",05618-000
1,AUTO POSTO ESTORIL LTDA,São Paulo,São Paulo,Butantã,"Rua Alvarenga, 2045",05509-005
2,COMPLETA ALIMENTOS LTDA,Bahia,SALVADOR,ITAIGARA,"AV ANTONIO CARLOS MAGALHAES, 1370, SALVADOR, B...",41830-355
3,POSTO Z + Z STELLA MARIS LTDA,Bahia,SALVADOR,STELLA MARIS,"AL DILSON J FONSEC, 1248 LT 57 QD D, SALVADOR,...",41600-100
4,AUTO POSTO MARINI LTDA,São Paulo,SAO PAULO,FREGUESIA DO O,"AV INAJAR DE SOUZA, 550, SAO PAULO, São Paulo ...",02716-000

In [3]:

# Função para obter coordenadas
def obter_coordenadas(cep):
    try:
        location = geolocator.geocode({"postalcode": cep, "country": "Brazil"})
        if location:
            return location.latitude, location.longitude
    except Exception as e:
        print(f"Erro ao buscar coordenadas para o CEP {cep}: {e}")
    return None, None

# Adicionar colunas de latitude e longitude
df['Latitude'], df['Longitude'] = zip(*df['CEP'].astype(str).apply(obter_coordenadas))

df.head()

,Nome da tela / nome do local,UF,Cidade,Bairro,Endereço,CEP,Latitude,Longitude
0,CONV ESTADIO DO GUEDALA LTDA,São Paulo,SAO PAULO,MORUMBI (VILA PROGREDIOR),"AVENIDA JORGE JOÃO SAAD, 161/165, SAO PAULO, S...",05618-000,-23.588981,-46.722411
1,AUTO POSTO ESTORIL LTDA,São Paulo,São Paulo,Butantã,"Rua Alvarenga, 2045",05509-005,-23.563497,-46.712076
2,COMPLETA ALIMENTOS LTDA,Bahia,SALVADOR,ITAIGARA,"AV ANTONIO CARLOS MAGALHAES, 1370, SALVADOR, B...",41830-355,NaN,NaN
3,POSTO Z + Z STELLA MARIS LTDA,Bahia,SALVADOR,STELLA MARIS,"AL DILSON J FONSEC, 1248 LT 57 QD D, SALVADOR,...",41600-100,NaN,NaN
4,AUTO POSTO MARINI LTDA,São Paulo,SAO PAULO,FREGUESIA DO O,"AV INAJAR DE SOUZA, 550, SAO PAULO, São Paulo ...",02716-000,-23.492447,-46.682565

In [6]:
df_na_values = df[df[['Latitude', 'Longitude']].isna().any(axis=1)]
df_na_values.head(100)

,Nome da tela / nome do local,UF,Cidade,Bairro,Endereço,CEP,Latitude,Longitude
2,COMPLETA ALIMENTOS LTDA,Bahia,SALVADOR,ITAIGARA,"AV ANTONIO CARLOS MAGALHAES, 1370, SALVADOR, B...",41830-355,NaN,NaN
3,POSTO Z + Z STELLA MARIS LTDA,Bahia,SALVADOR,STELLA MARIS,"AL DILSON J FONSEC, 1248 LT 57 QD D, SALVADOR,...",41600-100,NaN,NaN
5,ARINELLA INTERLAGOS COM VAR COMB LT,São Paulo,SAO PAULO,JD CONSORCIO,"AV INTERLAGOS, 1676, SAO PAULO, São Paulo 0466...",04660-002,NaN,NaN
10,POSTO FIJI COM COMB LTDA,Pernambuco,RECIFE,TORROES,"AV ENG ABIDIAS DE CARVALHO, 1122, RECIFE, Pern...",50720-225,NaN,NaN
13,LOJA CONVENIENCIA VOLTA AO MUNDO LT,Pernambuco,RECIFE,CAXANGA,"AV JOAQUIM RIBEIRO,40 ESQ V AO MUND, RECIFE, P...",50980-000,NaN,NaN
...,...,...,...,...,...,...,...,...
189,PAGUE MENOS,BA,SALVADOR,SUSSUARANA,AV. ULYSSES GUIMARÃES 2360,41218-700,NaN,NaN
190,PAGUE MENOS,BA,SALVADOR,BARRA,AV CENTENÁRIO SHOPPING BARRA 159,40149-900,NaN,NaN
191,PAGUE MENOS,BA,SALVADOR,GRACA,RUA DA GRAÇA 30,40150-055,NaN,NaN
197,EXTRAFARMA,BA,SALVADOR,CAMINHO DAS ARVORES,AV TANCREDO NEVES 3133,41100-800,NaN,NaN
199,EXTRAFARMA,BA,SALVADOR,NAZARE,AV JOANA ANGÉLICA 874,40050-340,NaN,NaN

In [4]:
# Salvar o arquivo atualizado
output_path = r'C:\Users\Administrator\Documents\projetos_py\unlimitail\Blocos e Trios elétricos - CEP.xlsx'
df.to_excel(output_path, index=False)

# import ace_tools as tools; tools.display_dataframe_to_user(name="Blocos e Trios Elétricos com Coordenadas", dataframe=df)